name: Create docs

on:
  workflow_dispatch:
  push:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Docs
    runs-on: windows-2019
    steps:

      # Clone Geode repo
      - name: Checkout Geode repo
        uses: actions/checkout@v3
        with:
          repository: 'geode-sdk/geode'
          path: 'geode'

      - name: Checkout docs repo
        uses: actions/checkout@v3
        with:
          path: 'geode/docs'
      
      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      
      - name: Download Flash
        uses: robinraju/release-downloader@v1.5
        with:
          repository: hjfod/flash
          latest: true
          fileName: "flash.exe"
          tarBall: false
          zipBall: false
          out-file-path: "" 
      
      - name: Create dist directory
        run: |
          mkdir dist
        
      - name: Build docs with Flash
        run: |
          cd dist 
          ./../flash.exe -i ../geode -o . 

      - name: Setup Pages
        uses: actions/configure-pages@v2
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './dist'
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
